version: '3'

services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
        - shk.Fullstack.Template
    ports:
        - 6379:6379
    volumes:
        - redis:/data/redis

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=changeme
    networks:
        - shk.Fullstack.Template
    ports:
        - 5432:5432
    volumes:
        - postgres:/data/postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.ru
        - PGADMIN_DEFAULT_PASSWORD=admin
        - PGADMIN_LISTEN_PORT=5050
        - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
        - pgadmin:/var/lib/pgadmin
    ports:
        - 5050:5050
    networks:
        - shk.Fullstack.Template
    restart: unless-stopped

networks:
  shk.Fullstack.Template:
    name: shk.Fullstack.Template

volumes:
  redis:
  postgres:
  pgadmin:
    driver: local